version: "3"

services:

  f05_backend:
    build: ./
    volumes:
      - ./images/:/f05_backend/images
      - ./f05_backend.env:/f05_backend/f05_backend.env
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - postgres-compose-network

  database:
    image: postgres
    env_file:
      - database.env # configure postgres
    ports:
      - "15432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - postgres-compose-network

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "walterjgsp@dcc.ufmg.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2020!"
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - postgres-compose-network

volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  postgres-compose-network:
    driver: bridge