"""first migration

Revision ID: 321b7d5554d9
Revises: 
Create Date: 2022-10-09 21:59:14.123390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321b7d5554d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_publicwork_id', table_name='publicwork')
    op.drop_table('publicwork')
    op.drop_table('transaction')
    op.drop_table('association_type_ph_pw')
    op.drop_index('ix_photo_id', table_name='photo')
    op.drop_table('photo')
    op.drop_index('ix_association_type_ph_pw_version_end_transaction_id', table_name='association_type_ph_pw_version')
    op.drop_index('ix_association_type_ph_pw_version_operation_type', table_name='association_type_ph_pw_version')
    op.drop_index('ix_association_type_ph_pw_version_transaction_id', table_name='association_type_ph_pw_version')
    op.drop_table('association_type_ph_pw_version')
    op.drop_index('ix_inspection_version_end_transaction_id', table_name='inspection_version')
    op.drop_index('ix_inspection_version_flag', table_name='inspection_version')
    op.drop_index('ix_inspection_version_operation_type', table_name='inspection_version')
    op.drop_index('ix_inspection_version_transaction_id', table_name='inspection_version')
    op.drop_table('inspection_version')
    op.drop_index('ix_typework_version_end_transaction_id', table_name='typework_version')
    op.drop_index('ix_typework_version_flag', table_name='typework_version')
    op.drop_index('ix_typework_version_operation_type', table_name='typework_version')
    op.drop_index('ix_typework_version_transaction_id', table_name='typework_version')
    op.drop_table('typework_version')
    op.drop_index('ix_typephoto_flag', table_name='typephoto')
    op.drop_table('typephoto')
    op.drop_index('ix_publicwork_version_end_transaction_id', table_name='publicwork_version')
    op.drop_index('ix_publicwork_version_id', table_name='publicwork_version')
    op.drop_index('ix_publicwork_version_operation_type', table_name='publicwork_version')
    op.drop_index('ix_publicwork_version_transaction_id', table_name='publicwork_version')
    op.drop_table('publicwork_version')
    op.drop_index('ix_inspection_flag', table_name='inspection')
    op.drop_table('inspection')
    op.drop_index('ix_association_tw_ws_version_end_transaction_id', table_name='association_tw_ws_version')
    op.drop_index('ix_association_tw_ws_version_operation_type', table_name='association_tw_ws_version')
    op.drop_index('ix_association_tw_ws_version_transaction_id', table_name='association_tw_ws_version')
    op.drop_table('association_tw_ws_version')
    op.drop_index('ix_typework_flag', table_name='typework')
    op.drop_table('typework')
    op.drop_index('ix_workstatus_flag', table_name='workstatus')
    op.drop_table('workstatus')
    op.drop_index('ix_city_codigo_ibge', table_name='city')
    op.drop_table('city')
    op.drop_index('ix_workstatus_version_end_transaction_id', table_name='workstatus_version')
    op.drop_index('ix_workstatus_version_flag', table_name='workstatus_version')
    op.drop_index('ix_workstatus_version_operation_type', table_name='workstatus_version')
    op.drop_index('ix_workstatus_version_transaction_id', table_name='workstatus_version')
    op.drop_table('workstatus_version')
    op.drop_table('association_tw_ws')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_city_version_codigo_ibge', table_name='city_version')
    op.drop_index('ix_city_version_end_transaction_id', table_name='city_version')
    op.drop_index('ix_city_version_operation_type', table_name='city_version')
    op.drop_index('ix_city_version_transaction_id', table_name='city_version')
    op.drop_table('city_version')
    op.drop_index('ix_address_id', table_name='address')
    op.drop_table('address')
    op.drop_index('ix_collect_id', table_name='collect')
    op.drop_table('collect')
    op.drop_index('ix_typephoto_version_end_transaction_id', table_name='typephoto_version')
    op.drop_index('ix_typephoto_version_flag', table_name='typephoto_version')
    op.drop_index('ix_typephoto_version_operation_type', table_name='typephoto_version')
    op.drop_index('ix_typephoto_version_transaction_id', table_name='typephoto_version')
    op.drop_table('typephoto_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typephoto_version',
    sa.Column('flag', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('flag', 'transaction_id')
    )
    op.create_index('ix_typephoto_version_transaction_id', 'typephoto_version', ['transaction_id'], unique=False)
    op.create_index('ix_typephoto_version_operation_type', 'typephoto_version', ['operation_type'], unique=False)
    op.create_index('ix_typephoto_version_flag', 'typephoto_version', ['flag'], unique=False)
    op.create_index('ix_typephoto_version_end_transaction_id', 'typephoto_version', ['end_transaction_id'], unique=False)
    op.create_table('collect',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.INTEGER(), nullable=True),
    sa.Column('comments', sa.VARCHAR(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.Column('public_work_status', sa.INTEGER(), nullable=True),
    sa.Column('public_work_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['public_work_id'], ['publicwork.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collect_id', 'collect', ['id'], unique=False)
    op.create_table('address',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('street', sa.VARCHAR(), nullable=True),
    sa.Column('neighborhood', sa.VARCHAR(), nullable=True),
    sa.Column('number', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('cep', sa.VARCHAR(), nullable=True),
    sa.Column('public_work_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_address_id', 'address', ['id'], unique=False)
    op.create_table('city_version',
    sa.Column('codigo_ibge', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('uf', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_ibge', 'transaction_id')
    )
    op.create_index('ix_city_version_transaction_id', 'city_version', ['transaction_id'], unique=False)
    op.create_index('ix_city_version_operation_type', 'city_version', ['operation_type'], unique=False)
    op.create_index('ix_city_version_end_transaction_id', 'city_version', ['end_transaction_id'], unique=False)
    op.create_index('ix_city_version_codigo_ibge', 'city_version', ['codigo_ibge'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('cpf', sa.VARCHAR(), nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(), nullable=True),
    sa.Column('birthday', sa.INTEGER(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_table('association_tw_ws',
    sa.Column('type_work_flag', sa.INTEGER(), nullable=False),
    sa.Column('work_status_flag', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['type_work_flag'], ['typework.flag'], ),
    sa.ForeignKeyConstraint(['work_status_flag'], ['workstatus.flag'], ),
    sa.PrimaryKeyConstraint('type_work_flag', 'work_status_flag')
    )
    op.create_table('workstatus_version',
    sa.Column('flag', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('flag', 'transaction_id')
    )
    op.create_index('ix_workstatus_version_transaction_id', 'workstatus_version', ['transaction_id'], unique=False)
    op.create_index('ix_workstatus_version_operation_type', 'workstatus_version', ['operation_type'], unique=False)
    op.create_index('ix_workstatus_version_flag', 'workstatus_version', ['flag'], unique=False)
    op.create_index('ix_workstatus_version_end_transaction_id', 'workstatus_version', ['end_transaction_id'], unique=False)
    op.create_table('city',
    sa.Column('codigo_ibge', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('uf', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('codigo_ibge')
    )
    op.create_index('ix_city_codigo_ibge', 'city', ['codigo_ibge'], unique=False)
    op.create_table('workstatus',
    sa.Column('flag', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('flag')
    )
    op.create_index('ix_workstatus_flag', 'workstatus', ['flag'], unique=False)
    op.create_table('typework',
    sa.Column('flag', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('flag')
    )
    op.create_index('ix_typework_flag', 'typework', ['flag'], unique=False)
    op.create_table('association_tw_ws_version',
    sa.Column('type_work_flag', sa.INTEGER(), nullable=False),
    sa.Column('work_status_flag', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('type_work_flag', 'work_status_flag', 'transaction_id')
    )
    op.create_index('ix_association_tw_ws_version_transaction_id', 'association_tw_ws_version', ['transaction_id'], unique=False)
    op.create_index('ix_association_tw_ws_version_operation_type', 'association_tw_ws_version', ['operation_type'], unique=False)
    op.create_index('ix_association_tw_ws_version_end_transaction_id', 'association_tw_ws_version', ['end_transaction_id'], unique=False)
    op.create_table('inspection',
    sa.Column('flag', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('public_work_id', sa.VARCHAR(), nullable=True),
    sa.Column('collect_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('flag')
    )
    op.create_index('ix_inspection_flag', 'inspection', ['flag'], unique=False)
    op.create_table('publicwork_version',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('type_work_flag', sa.INTEGER(), nullable=True),
    sa.Column('address_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_status', sa.INTEGER(), nullable=True),
    sa.Column('rnn_status', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index('ix_publicwork_version_transaction_id', 'publicwork_version', ['transaction_id'], unique=False)
    op.create_index('ix_publicwork_version_operation_type', 'publicwork_version', ['operation_type'], unique=False)
    op.create_index('ix_publicwork_version_id', 'publicwork_version', ['id'], unique=False)
    op.create_index('ix_publicwork_version_end_transaction_id', 'publicwork_version', ['end_transaction_id'], unique=False)
    op.create_table('typephoto',
    sa.Column('flag', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('flag')
    )
    op.create_index('ix_typephoto_flag', 'typephoto', ['flag'], unique=False)
    op.create_table('typework_version',
    sa.Column('flag', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('flag', 'transaction_id')
    )
    op.create_index('ix_typework_version_transaction_id', 'typework_version', ['transaction_id'], unique=False)
    op.create_index('ix_typework_version_operation_type', 'typework_version', ['operation_type'], unique=False)
    op.create_index('ix_typework_version_flag', 'typework_version', ['flag'], unique=False)
    op.create_index('ix_typework_version_end_transaction_id', 'typework_version', ['end_transaction_id'], unique=False)
    op.create_table('inspection_version',
    sa.Column('flag', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('public_work_id', sa.VARCHAR(), nullable=True),
    sa.Column('collect_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('user_email', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('flag', 'transaction_id')
    )
    op.create_index('ix_inspection_version_transaction_id', 'inspection_version', ['transaction_id'], unique=False)
    op.create_index('ix_inspection_version_operation_type', 'inspection_version', ['operation_type'], unique=False)
    op.create_index('ix_inspection_version_flag', 'inspection_version', ['flag'], unique=False)
    op.create_index('ix_inspection_version_end_transaction_id', 'inspection_version', ['end_transaction_id'], unique=False)
    op.create_table('association_type_ph_pw_version',
    sa.Column('type_work_flag', sa.INTEGER(), nullable=False),
    sa.Column('type_photo_flag', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('end_transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), nullable=False),
    sa.PrimaryKeyConstraint('type_work_flag', 'type_photo_flag', 'transaction_id')
    )
    op.create_index('ix_association_type_ph_pw_version_transaction_id', 'association_type_ph_pw_version', ['transaction_id'], unique=False)
    op.create_index('ix_association_type_ph_pw_version_operation_type', 'association_type_ph_pw_version', ['operation_type'], unique=False)
    op.create_index('ix_association_type_ph_pw_version_end_transaction_id', 'association_type_ph_pw_version', ['end_transaction_id'], unique=False)
    op.create_table('photo',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('filepath', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('collect_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['collect_id'], ['collect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photo_id', 'photo', ['id'], unique=False)
    op.create_table('association_type_ph_pw',
    sa.Column('type_work_flag', sa.INTEGER(), nullable=False),
    sa.Column('type_photo_flag', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['type_photo_flag'], ['typephoto.flag'], ),
    sa.ForeignKeyConstraint(['type_work_flag'], ['typework.flag'], ),
    sa.PrimaryKeyConstraint('type_work_flag', 'type_photo_flag')
    )
    op.create_table('transaction',
    sa.Column('issued_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('remote_addr', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicwork',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('type_work_flag', sa.INTEGER(), nullable=True),
    sa.Column('address_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_status', sa.INTEGER(), nullable=True),
    sa.Column('rnn_status', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['type_work_flag'], ['typework.flag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_publicwork_id', 'publicwork', ['id'], unique=False)
    # ### end Alembic commands ###
